const mysql = require('mysql');
require('dotenv').config();
let partyArr = [
  "Bharatiya Janata Party",
  "Biju Janata Dal",
  "Indian National Congress",
  "Manas Lokshakti Dal",
  "Independent",
  "Bahujan Samaj Party",
  "National Jan Dal",
  "Kalinga Sena",
  "None of the Above",
  "Independent",
  "Biju Janata Dal",
  "Independent",
  "Akhil Bhartiya Parivar Party",
  "Bahujan Samaj Party",
  "Bharatiya Janata Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Odisha Janata Party",
  "Indian National Congress",
  "None of the Above",
  "Bharatiya Janata Party",
  "Biju Janata Dal",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Independent",
  "Manas Lokshakti Dal",
  "Bahujan Samaj Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "AJSU Party",
  "None of the Above",
  "Indian National Congress",
  "Biju Janata Dal",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "Communist Party of India  (Marxist-Leninist)  (Liberation)",
  "Independent",
  "Independent",
  "Naba Bharata Nirmana Seva Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Republican Party of India (A)",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "Jharkhand Mukti Morcha",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "AJSU Party",
  "Independent",
  "Biju Janata Dal",
  "None of the Above",
  "Biju Janata Dal",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Biju Janata Dal",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Biju Janata Dal",
  "Indian National Congress",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "National Jan Dal",
  "Independent",
  "Paschimanchal Vikas Party",
  "Rashtriya Manav Party",
  "Kosal Janata Dal",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Biju Janata Dal",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Naba Bharata Nirmana Seva Party",
  "National Apni Party",
  "Jharkhand Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Naam Tamilar Katchi",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "United Republican Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Aam Aadmi Party",
  "Shiromani Akali Dal",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Independent",
  "Independent",
  "Communist Party of India",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Aas Punjab Party",
  "Independent",
  "Independent",
  "Aam Janta Party (India)",
  "Independent",
  "Independent",
  "Shiromani Lok Dal Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Republican Party of India (Athawale)",
  "Sacho Sach Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Aam Aadmi Party",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Shiromani Akali Dal",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Akhil Bhartiya Parivar Party",
  "Bharatheeya Jawan Kisan Party",
  "Democratic Bharatiya Samaj Party",
  "Bhartiya Rashtriya Dal",
  "Independent",
  "Bhartiya Jan Samman Party",
  "Independent",
  "Independent",
  "Ekam Sanatan Bharat Dal",
  "Punjab National Party",
  "Independent",
  "Independent",
  "Revolutionary Socialist Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Hindustan Shakti Sena",
  "None of the Above",
  "Shiromani Akali Dal",
  "Aam Aadmi Party",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Aazad Samaj Party (Kanshi Ram)",
  "Jan Sewa Driver Party",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "Independent",
  "Nationalist Justice Party",
  "Independent",
  "None of the Above",
  "Independent",
  "Aam Aadmi Party",
  "Shiromani Akali Dal",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Communist Party of India",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Independent",
  "Nationalist Justice Party",
  "Bhartiya Rashtriya Dal",
  "Independent",
  "Independent",
  "Jan Sewa Driver Party",
  "Independent",
  "Independent",
  "Rashtriya Republican Party",
  "Independent",
  "Apna Samaj Party",
  "Independent",
  "Democratic Bharatiya Samaj Party",
  "Sanjhi Virasat Party",
  "Bahujan Mukti Party",
  "Republican Party of India",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Aam Aadmi Party",
  "Bharatiya Janata Party",
  "Shiromani Akali Dal",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Shiromani Akali Dal",
  "Aam Aadmi Party",
  "Bharatiya Janata Party",
  "Independent",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Nationalist Justice Party",
  "Punjab National Party",
  "Rashtriya Republican Party",
  "Independent",
  "Independent",
  "Republican Party of India (Athawale)",
  "Independent",
  "India Praja Bandhu Party",
  "Independent",
  "Independent",
  "Jan Sewa Driver Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Aam Aadmi Party",
  "Shiromani Akali Dal",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "Megh Desham Party",
  "Independent",
  "Independent",
  "National Republic Party Of India",
  "Jan Sewa Driver Party",
  "Independent",
  "Independent",
  "Bhartiya Rashtriya Dal",
  "Nationalist Justice Party",
  "None of the Above",
  "Aam Aadmi Party",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Shiromani Akali Dal",
  "Bahujan Samaj Party",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Bahujan Dravida Party",
  "Independent",
  "Democratic Bharatiya Samaj Party",
  "Independent",
  "Independent",
  "Nationalist Justice Party",
  "Samaj Bhalai Morcha",
  "Independent",
  "Bahujan Mukti Party",
  "Global Republican Party",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Aam Aadmi Party",
  "Shiromani Akali Dal",
  "Bahujan Samaj Party",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Republican Party of India (Athawale)",
  "Peoples Party of India (Democratic)",
  "Democratic Bharatiya Samaj Party",
  "Independent",
  "Apna Samaj Party",
  "Independent",
  "Global Republican Party",
  "Independent",
  "Loktantrik Lok Rajyam Party",
  "None of the Above",
  "Independent",
  "Indian National Congress",
  "Aam Aadmi Party",
  "Shiromani Akali Dal",
  "Bharatiya Janata Party",
  "Independent",
  "Aas Punjab Party",
  "Bahujan Samaj Party",
  "Independent",
  "Communist Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "All India Mazdoor Party (Rangreta)",
  "Sanjhi Virasat Party",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Aam Aadmi Party",
  "Shiromani Akali Dal",
  "Independent",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Sunahara Bharat Party",
  "Bahujan Dravida Party",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "Jan Sewa Driver Party",
  "Independent",
  "Independent",
  "Independent",
  "Sehajdhari Sikh Party",
  "Independent",
  "Independent",
  "Independent",
  "Samajik Sangharsh Party",
  "Independent",
  "Independent",
  "Hindustan Shakti Sena",
  "Aam Lok Party United",
  "Independent",
  "Independent",
  "Bharatiya Inqalab Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Global Republican Party",
  "Independent",
  "Nationalist Justice Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Aam Aadmi Party",
  "Bharatiya Janata Party",
  "Shiromani Akali Dal",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "Akhil Bhartiya Parivar Party",
  "Independent",
  "Independent",
  "Jan Janwadi Party",
  "Independent",
  "Independent",
  "Independent",
  "Hindustan Shakti Sena",
  "Independent",
  "Revolutionary Socialist Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Aam Aadmi Party",
  "Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Shiromani Akali Dal",
  "Bahujan Samaj Party",
  "Apni Ekta Party",
  "Independent",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Independent",
  "Adarsh Janta Party,",
  "Independent",
  "Independent",
  "Nationalist Justice Party",
  "Independent",
  "Aam Janta Party (India)",
  "Bhartiya Jan Samman Party",
  "Punjab National Party",
  "Independent",
  "Independent",
  "Independent",
  "India Greens Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Bharatiya Yuva Jan Ekta Party",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Independent",
  "National Future Party",
  "Independent",
  "Independent",
  "Akhil Bhartiya Aamjan Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Sarv Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Hindustan Janta Party",
  "None of the Above",
  "Bharat Adivasi Party",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Independent",
  "Indian Peoples Green Party",
  "Bahujan Samaj Party",
  "None of the Above",
  "Indian National Congress",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Independent",
  "Aazad Samaj Party (Kanshi Ram)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Viro Ke Vir Indian Party",
  "Independent",
  "Independent",
  "Right to Recall Party",
  "Independent",
  "Bhartiya Garib Vikas Kalyan Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bharat Adivasi Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Ekam Sanatan Bharat Dal",
  "Independent",
  "Akhil Bharatiya Congress Dal (Ambedkar)",
  "Independent",
  "Independent",
  "Independent",
  "Right to Recall Party",
  "Independent",
  "Pehchan People’s Party",
  "Vishva Shakti Party",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Bharat Rakshak Party (Democratic)",
  "Independent",
  "Independent",
  "Independent",
  "National Janmandal Party",
  "Independent",
  "Independent",
  "Bheem Tribal Congress",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Indian Peoples Green Party",
  "Independent",
  "Independent",
  "Bhartiya Jan Samman Party",
  "Jai Hind Congress Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Rashtriya Sanatan Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Indian Peoples Green Party",
  "Bheem Tribal Congress",
  "Right to Recall Party",
  "Rashtriya Samta Vikas Party",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "Ambedkarite Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Republican Party of India (A)",
  "Independent",
  "Bheem Tribal Congress",
  "Right to Recall Party",
  "Rashtriya Sawarn Dal",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Independent",
  "Bharat Adivasi Party",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bheem Tribal Congress",
  "Indian Peoples Green Party",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Right to Recall Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "Ambedkarite Party of India",
  "Independent",
  "Bahujan Kranti Party (Marxwad-Ambedkarwad)",
  "Bheem Tribal Congress",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Independent",
  "Independent",
  "Right to Recall Party",
  "Bharatiya Sampuran Krantikari Party",
  "Indian Peoples Green Party",
  "Dalit Kranti Dal",
  "Rashtriya Janshakti Party (Secular)",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Ekam Sanatan Bharat Dal",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "Independent",
  "Independent",
  "Right to Recall Party",
  "Independent",
  "None of the Above",
  "Rashtriya Loktantrik Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Abhinav Rajasthan Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Rashtriya Janshakti Party (Secular)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Bharat Adivasi Party",
  "Independent",
  "Independent",
  "Indian Peoples Green Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Bhartiya Jan Adhikar Party",
  "Independent",
  "Bheem Tribal Congress",
  "Independent",
  "None of the Above",
  "Communist Party of India  (Marxist)",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Ambedkarite Party of India",
  "Ummeed Party of India",
  "Rashtriya Sawarn Dal",
  "Independent",
  "Independent",
  "Bharatiya Yuva Jan Ekta Party",
  "Bhartiya Party",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Indian Peoples Green Party",
  "Independent",
  "Independent",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Rajasthan Raj Party",
  "Bharat Adivasi Party",
  "Bheem Tribal Congress",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bharat Adivasi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Indian Peoples Green Party",
  "Independent",
  "None of the Above",
  "Sikkim Krantikari Morcha",
  "Sikkim Democratic Front",
  "Citizen Action Party-Sikkim",
  "Independent",
  "Bharatiya Janata Party",
  "Sikkim Republican Party",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Pattali Makkal Katchi",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Anna MGR Dravida Makkal Kalgam",
  "Tamil Manila Murpokku Dravida Kazhagam",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "United Republican Party of India",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "All India Jananayaka Makkal Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "United Republican Party of India",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Thakkam Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Pattali Makkal Katchi",
  "Independent",
  "Independent",
  "Viro Ke Vir Indian Party",
  "Anna MGR Dravida Makkal Kalgam",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Thakkam Katchi",
  "Desiya Murpokku Dravida Kazhagam",
  "Independent",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Anti Corruption Dynamic Party",
  "Independent",
  "Tamilnadu Makkal Nalvazhvu Periyakkam",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Tipu Sultan Party",
  "Independent",
  "Chennai Youth Party",
  "Independent",
  "Bahujan Samaj Party",
  "Desiya Makkal Sakthi Katchi",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Republican Party of India  (Sivaraj)",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Thakkam Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Independent",
  "Tamizhaga Murpokku Makkal Katchi",
  "Thakkam Katchi",
  "Mahathma Makkal Munnetra Kazhakam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Desiya Makkal Sakthi Katchi",
  "Independent",
  "Independent",
  "Aravor Munnetra Kazhagam",
  "National Maha Sabha Party",
  "Jebamani Janata",
  "Bahujan Samaj Party",
  "Viro Ke Vir Indian Party",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Bahujan Samaj Party",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Naadaalum Makkal Katchi",
  "Independent",
  "None of the Above",
  "Independent",
  "Hindustan Janta Party",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Viro Ke Vir Indian Party",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Tamizhaga Murpokku Makkal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Ganasangam Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Rashtriya Samaj Paksha",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Desiya Murpokku Dravida Kazhagam",
  "Pattali Makkal Katchi",
  "Naam Tamilar Katchi",
  "Independent",
  "Anti Corruption Dynamic Party",
  "Independent",
  "Independent",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Desiya Makkal Sakthi Katchi",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "All India Anna Dravida Munnetra Kazhagam",
  "Pattali Makkal Katchi",
  "Naam Tamilar Katchi",
  "Dhesiya Makkal Kazhagam",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Ganasangam Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Tamilar Makkal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Communist Party of India  (Marxist)",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Pattali Makkal Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "All India Youth Development Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Ganasangam Party of India",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Anti Corruption Dynamic Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Anna Puratchi Thalaivar Amma Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Independent",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Ulzaipali Makkal Katchy",
  "Tamil Maanila Congress  (Moopanar)",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Desiya Makkal Sakthi Katchi",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Anna Makkal Katchi",
  "Pattali Makkal Katchi",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Pattali Makkal Katchi",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Bahujan Dravida Party",
  "Independent",
  "Punnagai Desam Party",
  "Independent",
  "Independent",
  "Thakkam Katchi",
  "Independent",
  "Indian National Congress",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "All India Anna Dravida Munnetra Kazhagam",
  "Bharatiya Janata Party",
  "Naam Tamilar Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Independent",
  "Ganasangam Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Anti Corruption Dynamic Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Viro Ke Vir Indian Party",
  "Naam Tamilar Katchi",
  "Anaithu India Makkal Katchi",
  "Independent",
  "Karunaadu Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Tamilar Makkal Katchi",
  "Aravor Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Chennai Youth Party",
  "Independent",
  "Bharatiya Praja Aikyata Party",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Communist Party of India  (Marxist)",
  "All India Anna Dravida Munnetra Kazhagam",
  "Bharatiya Janata Party",
  "Naam Tamilar Katchi",
  "Bharatiya Praja Aikyata Party",
  "United Republican Party of India",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Dravida Party",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Pattali Makkal Katchi",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Anna MGR Dravida Makkal Kalgam",
  "Independent",
  "Independent",
  "Independent",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Independent",
  "None of the Above",
  "Communist Party of India",
  "Bharatiya Janata Party",
  "Independent",
  "Desiya Makkal Sakthi Katchi",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Naam Tamilar Katchi",
  "None of the Above",
  "Independent",
  "Ganasangam Party of India",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Tamilaga Makkal Thannurimai Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Viduthalai Kalam Katchi",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Ulzaipali Makkal Katchy",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Ahimsa Socialist Party",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "Bharatiya Janata Party",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Ganasangam Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Ambedkarite Party of India",
  "Independent",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "All India Anna Dravida Munnetra Kazhagam",
  "Bharatiya Janata Party",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "New Generation People’s Party",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "None of the Above",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Bahujan Dravida Party",
  "Independent",
  "Independent",
  "Independent",
  "Indian Union Muslim League",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Independent",
  "Independent",
  "Puthiya Makkal Tamil Desam Katchi",
  "Independent",
  "Desiya Makkal Sakthi Katchi",
  "Independent",
  "None of the Above",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Dhesiya Makkal Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Pattali Makkal Katchi",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Aravor Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Ulzaipali Makkal Katchy",
  "Ambedkarite Party of India",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Vidiyalai Thedum Indhiyargal Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "None of the Above",
  "Independent",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Naadaalum Makkal Katchi",
  "Thakkam Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Desiya Makkal Sakthi Katchi",
  "Samaniya Makkal Nala Katchi",
  "Bahujan Samaj Party",
  "Independent",
  "Jebamani Janata",
  "Tamil Maanila Congress  (Moopanar)",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Mahathma Makkal Munnetra Kazhakam",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Tamizhaga Murpokku Makkal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Aravor Munnetra Kazhagam",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Bharatiya Janata Party",
  "Viro Ke Vir Indian Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Bahujan Dravida Party",
  "Desiya Makkal Sakthi Katchi",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "Desiya Murpokku Dravida Kazhagam",
  "Naam Tamilar Katchi",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "Amma Makkal Munnettra Kazagam",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "All India Youth Development Party",
  "Bahujan Samaj Party",
  "Humanity for Peace Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Desiya Murpokku Dravida Kazhagam",
  "Naam Tamilar Katchi",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Anna MGR Dravida Makkal Kalgam",
  "Desiya Makkal Sakthi Katchi",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "All India Anna Dravida Munnetra Kazhagam",
  "Tamil Maanila Congress  (Moopanar)",
  "Naam Tamilar Katchi",
  "Naam Indiar Party",
  "Independent",
  "Independent",
  "Independent",
  "Makkal Nalvaazhvuk Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Aanaithinthiya Jananayaka Pathukappu Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Puthiya Makkal Tamil Desam Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Marumalarchi Dravida Munnetra Kazhagam",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Amma Makkal Munnettra Kazagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naadaalum Makkal Katchi",
  "Bahujan Samaj Party",
  "Anna Puratchi Thalaivar Amma Dravida Munnetra Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Anna MGR Dravida Makkal Kalgam",
  "Independent",
  "Independent",
  "Independent",
  "Samaniya Makkal Nala Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Aravor Munnetra Kazhagam",
  "Independent",
  "Bharatiya Janata Party",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Independent",
  "Independent",
  "Puthiya Makkal Tamil Desam Katchi",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Nam India Naam Indiyar Katchi",
  "Independent",
  "Bahujan Samaj Party",
  "Bahujan Dravida Party",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Aanaithinthiya Jananayaka Pathukappu Kazhagam",
  "Independent",
  "Indian National Congress",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Tamilaga Makkal Thannurimai Katchi",
  "Independent",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Independent",
  "Communist Party of India",
  "Rashtriya Samaj Paksha",
  "Naam Tamilar Katchi",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "None of the Above",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Makkal Nala Kazhagam",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "Bharatiya Praja Aikyata Party",
  "All India Uzhavargal Uzhaippalargal Katchi",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Dravida Munnetra Kazhagam",
  "Independent",
  "Naadaalum Makkal Katchi",
  "Independent",
  "Viro Ke Vir Indian Party",
  "None of the Above",
  "Dravida Munnetra Kazhagam",
  "Bharatiya Janata Party",
  "All India Anna Dravida Munnetra Kazhagam",
  "Naam Tamilar Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Bharatiya Praja Aikyata Party",
  "Bahujan Samaj Party",
  "Independent",
  "United Republican Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Tamil Manila Murpokku Dravida Kazhagam",
  "Independent",
  "Independent",
  "Independent",
  "Ganasangam Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Naam Tamilar Katchi",
  "Independent",
  "Pattali Makkal Katchi",
  "Independent",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Independent",
  "United Republican Party of India",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "All India Anna Dravida Munnetra Kazhagam",
  "None of the Above",
  "Indian National Congress",
  "Desiya Murpokku Dravida Kazhagam",
  "Bharatiya Janata Party",
  "Naam Tamilar Katchi",
  "Independent",
  "Bharatiya Praja Aikyata Party",
  "Hindu Samaj Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Dravida Party",
  "Tamilaga Makkal Nala Katchi",
  "Independent",
  "Independent",
  "Independent",
  "All India People Development Party",
  "None of the Above",
  "Anna YSR Congress Party",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "Bharatiya Janata Party",
  "Bharat Rashtra Samithi",
  "Bahujan Samaj Party",
  "Independent",
  "Vidhyarthula Rajakiya Party",
  "Gondwana Dandkaranya Party",
  "India Praja Bandhu Party",
  "Dharma Samaj Party",
  "Indian National Congress",
  "None of the Above",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Pyramid Party of India",
  "Bahujan Samaj Party",
  "Bahujan Republican  Socialist Party",
  "Independent",
  "Independent",
  "National Nava Kranthi Party",
  "Independent",
  "Independent",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Jai Maha Bharath Party",
  "Prajavani  Party",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "National Maha Sabha Party",
  "Independent",
  "Socialist Party (India)",
  "Bharat Rashtra Samithi",
  "Independent",
  "Jai Bharat National Party",
  "Telangana Rashtra Punahnirmana Samithi",
  "Independent",
  "Independent",
  "Independent",
  "Telangana Republican Party",
  "Independent",
  "Jai Swaraj Party",
  "Independent",
  "People Protection Party",
  "Communist Party of India  (Marxist)",
  "Social Justice Party of India",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "None of the Above",
  "Independent",
  "Independent",
  "India Praja Bandhu Party",
  "Independent",
  "Revolutionary Socialist Party",
  "Bharat Rashtra Samithi",
  "Praja Velugu Party",
  "Independent",
  "Independent",
  "Independent",
  "Socialist Party (India)",
  "Independent",
  "Rashtra Samanya Praja Party",
  "Blue India Party",
  "Independent",
  "Rashtriya Praja Congress  (Secular)",
  "Jai Swaraj Party",
  "All India Forward Bloc",
  "Independent",
  "Independent",
  "Independent",
  "Social Justice Party of India",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Telangana Republican Party",
  "Yuga Thulasi Party",
  "Independent",
  "Independent",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Desh Janhit Party",
  "Independent",
  "Marxist Communist Party of India (United)",
  "Bahujan Mukti Party",
  "All India Majlis-E-Inquilab-E-Millat",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Praja Ektha Party",
  "None of the Above",
  "Independent",
  "Indian National Yuva Jana Party",
  "Yuga Thulasi Party",
  "All India Majlis-E-Ittehadul Muslimeen",
  "Bahujan Mukti Party",
  "Independent",
  "Praja Ektha Party",
  "Indian Praja Congress",
  "Maa Telangana Party",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Yuva Taram Party",
  "Bahujan Samaj Party",
  "Independent",
  "All India Majlis-E-Inquilab-E-Millat",
  "Sakala Janula Party",
  "Bharatiya Janata Party",
  "Independent",
  "Socialist Party (India)",
  "Viduthalai Chiruthaigal Katchi",
  "Telangana Jaghir Party",
  "Telangana Prajaa Jeevana Rythu Party",
  "Independent",
  "All India Mahila Empowerment Party",
  "Dalita Bahujana Party",
  "Bharat Rashtra Samithi",
  "Dharma Samaj Party",
  "Independent",
  "Indian National Congress",
  "Vidhyarthula Rajakiya Party",
  "None of the Above",
  "Independent",
  "Telugu Congress Party",
  "Independent",
  "Bharatiya Janata Party",
  "Pyramid Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Bharathiya YuvaKula Dalam",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Bahujan Mukti Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Independent",
  "Social Justice Party of India",
  "Independent",
  "Independent",
  "National Nava Kranthi Party",
  "Socialist Party (India)",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "None of the Above",
  "Independent",
  "Sakala Janula Party",
  "Independent",
  "Independent",
  "Bharat Rashtra Samithi",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Pyramid Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Jai Bharat National Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Jaibhim Rao Bharat Party",
  "Independent",
  "Independent",
  "Independent",
  "Bahujana Left Party",
  "Independent",
  "Independent",
  "Independent",
  "Socialist Party (India)",
  "Independent",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "None of the Above",
  "Telangana Jaghir Party",
  "Independent",
  "Bharatiya Janata Party",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "Independent",
  "Socialist Party (India)",
  "Independent",
  "Independent",
  "Indian National Congress",
  "Gondwana Dandkaranya Party",
  "Independent",
  "Bharat Rashtra Samithi",
  "Dharma Samaj Party",
  "Independent",
  "Independent",
  "Blue India Party",
  "Independent",
  "Independent",
  "All India Forward Bloc",
  "Gondvana Gantantra Party",
  "Bahujan Samaj Party",
  "Independent",
  "None of the Above",
  "Independent",
  "Social Justice Party of India",
  "Independent",
  "Bharatiya Janata Party",
  "Telangana Jaghir Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Jai Swaraj Party",
  "Independent",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Mukti Party",
  "Independent",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Vidhyarthula Rajakiya Party",
  "Independent",
  "Independent",
  "Bharathiya YuvaKula Dalam",
  "Rashtra Samanya Praja Party",
  "Independent",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Bharat Rashtra Samithi",
  "Telangana Republican Party",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Dharma Samaj Party",
  "Jai Bharat National Party",
  "Independent",
  "Social Justice Party of India",
  "None of the Above",
  "Independent",
  "Independent",
  "Pyramid Party of India",
  "Independent",
  "Independent",
  "Indian National Congress",
  "National Nava Kranthi Party",
  "Independent",
  "Independent",
  "Independent",
  "Praja Velugu Party",
  "Independent",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "Independent",
  "Independent",
  "Telangana Praja Shakthi Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Jana Shankhaaraavam Party",
  "Independent",
  "India Praja Bandhu Party",
  "Independent",
  "Independent",
  "Bharat Jodo Party",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Pyramid Party of India",
  "Independent",
  "Bharat Rashtra Samithi",
  "Bahujan Mukti Party",
  "Independent",
  "Rashtriya Praja Congress  (Secular)",
  "Independent",
  "Indian National Congress",
  "Vidhyarthula Rajakiya Party",
  "Independent",
  "Bahujan Samaj Party",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "India Praja Bandhu Party",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Marxist Communist Party of India (United)",
  "Independent",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "Independent",
  "Socialist Party (India)",
  "Independent",
  "Independent",
  "Telangana Sakalajanula Party",
  "Independent",
  "Indian National Congress",
  "Independent",
  "None of the Above",
  "Independent",
  "Bahujan Mukti Party",
  "Independent",
  "Bharatiya Janata Party",
  "Yuga Thulasi Party",
  "Independent",
  "Independent",
  "Independent",
  "Anna YSR Congress Party",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Vidhyarthula Rajakiya Party",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "Dalita Bahujana Party",
  "Independent",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Independent",
  "Bahujana Left Party",
  "India Praja Bandhu Party",
  "Independent",
  "Indian National Congress",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Yuva Taram Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Anti Corruption Dynamic Party",
  "Independent",
  "Independent",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "New India Party",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Prajarajya Samithi",
  "Independent",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "Independent",
  "Rashtriya Manav Party",
  "Bahujan Mukti Party",
  "Independent",
  "Independent",
  "Independent",
  "Socialist Party (India)",
  "Independent",
  "Peoples Party of India (Democratic)",
  "Independent",
  "Independent",
  "Pyramid Party of India",
  "Dalita Bahujana Party",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Dharma Samaj Party",
  "Bharatiya Janata Party",
  "Social Justice Party of India",
  "Independent",
  "Independent",
  "Independent",
  "All India Majlis-E-Inquilab-E-Millat",
  "Independent",
  "Independent",
  "Indian National Yuva Jana Party",
  "Independent",
  "All India Backward People Sunami Party",
  "Independent",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "Independent",
  "Independent",
  "Socialist Party (India)",
  "Independent",
  "Telangana Rajya Samithi",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Jai Swaraj Party",
  "Independent",
  "Independent",
  "Independent",
  "Jai Bharat National Party",
  "Independent",
  "Anna YSR Congress Party",
  "Independent",
  "Independent",
  "Yuga Thulasi Party",
  "Pyramid Party of India",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Independent",
  "Pyramid Party of India",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Jai Bharat National Party",
  "Independent",
  "Independent",
  "Independent",
  "Jai Maha Bharath Party",
  "Independent",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "Independent",
  "Viduthalai Chiruthaigal Katchi",
  "Independent",
  "Bharat Rashtra Samithi",
  "Independent",
  "Independent",
  "Republican Party of India (Athawale)",
  "Independent",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Rashtriya Praja Congress  (Secular)",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Marxist Communist Party of India (United)",
  "Independent",
  "Dharma Samaj Party",
  "Independent",
  "Independent",
  "Mana Telangana Rashtra Samaikya Party",
  "Aihra National Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "None of the Above",
  "India Praja Bandhu Party",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Telangana Praja Shakthi Party",
  "Independent",
  "Independent",
  "Alliance of Democratic Reforms Party",
  "All India Forward Bloc",
  "Independent",
  "Pyramid Party of India",
  "Independent",
  "Bharatiya Janata Party",
  "Dharma Samaj Party",
  "Bharat Rashtra Samithi",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Republican Party of India (A)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Peoples Party of India (Democratic)",
  "Independent",
  "Bharatiya Kisan Parivartan Party",
  "Independent",
  "Bharatiya Majdoor Janta Party",
  "Independent",
  "Adarsh Samaj Party",
  "Lokpriya Rashtrawadi Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Sabhi Jan Party",
  "Independent",
  "Bhartiya Shakti Chetna Party",
  "Rashtriya Sanskriti Party",
  "Rashtriya Janutthan Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Saman Adhikar Party",
  "Independent",
  "Independent",
  "Moulik Adhikar Party",
  "Independent",
  "Independent",
  "Swatantra Jantaraj Party",
  "Loktantrik Janshakti Party",
  "Rashtriya Shoshit Samaj Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Apna Dal (Kamerawadi)",
  "Independent",
  "Pragatisheel Samaj Party",
  "Bhagidari Party(P)",
  "Peoples Party of India (Democratic)",
  "Independent",
  "Samyak Party",
  "Rashtriya Samaj Dal (R)",
  "Independent",
  "Kamera Samaj Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Bhagidari Party(P)",
  "Moolniwasi Samaj Party",
  "Peace Party",
  "Independent",
  "Bhartiya Shakti Chetna Party",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Janshakti Samta Party",
  "Independent",
  "Moulik Adhikar Party",
  "Independent",
  "Independent",
  "Independent",
  "Rashtriya Narayanwadi Vikas Party",
  "Samajhdar Party",
  "Sanyogwadi Party",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Akhil Bhartiya Parivar Party",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Peace Party",
  "Bharat Jodo Party",
  "Vanchitsamaj Insaaf Party",
  "Independent",
  "Sardar Patel Siddhant Party",
  "Bhartiya Shakti Chetna Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Moulik Adhikar Party",
  "Jan Raajya Party",
  "Independent",
  "Independent",
  "Independent",
  "Moolniwasi Samaj Party",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Log Party",
  "Swaraj Bhartiya Nyay Party",
  "Bahujan Samaj Party",
  "Independent",
  "Samajwadi Party",
  "Rashtriya Shoshit Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Rashtriya Lok Dal",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Azad Adhikar Sena",
  "Sarvjan Samta Party",
  "Sarvjan Lok Shakti Party",
  "Swatantra Jantaraj Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Bhartiya Awam Party (Rastriya)",
  "Independent",
  "Independent",
  "Independent",
  "Rashtra Dharak Dal",
  "Sardar Patel Siddhant Party",
  "Independent",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Sardar Patel Siddhant Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Gondvana Gantantra Party",
  "Independent",
  "Samajwadi Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Communist Party of India",
  "Bhagidari Party(P)",
  "Rashtra Uday Party",
  "Independent",
  "Swatantra Jantaraj Party",
  "Bhartiya Shakti Chetna Party",
  "Sardar Patel Siddhant Party",
  "Log Party",
  "Apna Dal (Kamerawadi)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Swatantrata Abhivyakti Party",
  "Independent",
  "Independent",
  "Public Adhikar Socialist Indian Party",
  "Independent",
  "Awami Samta Party",
  "Sardar Patel Siddhant Party",
  "Dr. Bhimrao Ambedkar Dal",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Peace Party",
  "Independent",
  "Peoples Party of India (Democratic)",
  "Independent",
  "Jan Shakti Ekta Party",
  "Independent",
  "Sardar Patel Siddhant Party",
  "Samrat Mihir Bhoj Samaj Party",
  "Independent",
  "Bharat Jodo Party",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Log Party",
  "Moulik Adhikar Party",
  "All India Forward Bloc",
  "Independent",
  "Independent",
  "Bharat Mahaparivar Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "All India Trinamool Congress",
  "Bahujan Samaj Party",
  "Pragatisheel Manav Samaj Party",
  "Sardar Patel Siddhant Party",
  "All India Forward Bloc",
  "Independent",
  "Rashtriya Samaj Paksha",
  "Rashtra Uday Party",
  "Independent",
  "None of the Above",
  "Rashtriya Lok Dal",
  "Bahujan Samaj Party",
  "Samajwadi Party",
  "Jai Samta Party",
  "Majloom Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Majdoor Kisan Union Party",
  "Peoples Party of India (Democratic)",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Rishivadi Karm Sheel Young Parmarthi Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Bhagidari Party(P)",
  "Jai Hind National Party",
  "Yuga Thulasi Party",
  "Independent",
  "Moulik Adhikar Party",
  "Sardar Patel Siddhant Party",
  "Samajhdar Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Janta Samta Party",
  "Rashtriya Samanta Dal",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Communist Party of India",
  "Political Justice Party",
  "Aam Janta Party (India)",
  "Lok Jan Sangharsh Party",
  "Independent",
  "Independent",
  "Peace Party",
  "Sardar Patel Siddhant Party",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Aazad Samaj Party (Kanshi Ram)",
  "Bahujan Samaj Party",
  "Peace Party",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Kisan Kranti Dal",
  "Independent",
  "Independent",
  "Peoples Party of India (Democratic)",
  "Bhartiya Shakti Chetna Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Samyak Party",
  "Independent",
  "Janta Samajwadi Party (Vivek Raj)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Communist Party of India",
  "Independent",
  "Moulik Adhikar Party",
  "Independent",
  "Bharat Mahaparivar Party",
  "Adarshwaadi Congress Party",
  "Rashtriya Janshakti Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Bharatiya Rashtriya Morcha",
  "Bharatiya Nagrik Party",
  "Independent",
  "Bharatheeya Jawan Kisan Party",
  "Bhartiya Shakti Chetna Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Rashtra Uday Party",
  "Parivartan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Akhil Bhartiya Parivar Party",
  "Peoples Party of India (Democratic)",
  "Vishwa Kalyan Rashtriya Manav Samaj Party",
  "Bhartiya Shakti Chetna Party",
  "Vikas Insaf Party",
  "Sardar Patel Siddhant Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Proutist Bloc, India",
  "Rashtriya Shoshit Samaj Party",
  "Bharatiya Majdoor Janta Party",
  "Rashtriya Jansanchar Dal",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Bharatiya Kisan Parivartan Party",
  "Rashtra Uday Party",
  "Parivartan Samaj Party",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Viro Ke Vir Indian Party",
  "Independent",
  "Independent",
  "Akhil Bhartiya Parivar Party",
  "National Party",
  "Bhartiya Rashtriya Jansatta",
  "Independent",
  "Independent",
  "Loktantrik Janshakti Party",
  "Super Power India Party",
  "Jai Hind National Party",
  "Subhashwadi Bhartiya Samajwadi Party (Subhas Party)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Rashtra Nirman Party",
  "Samaj Vikas Kranti Party",
  "Independent",
  "Independent",
  "Rashtriya Jan Karmath Party",
  "Right to Recall Party",
  "Subhashwadi Bhartiya Samajwadi Party (Subhas Party)",
  "None of the Above",
  "Independent",
  "Samajwadi Party",
  "Independent",
  "Bhartiya Lokvani Party",
  "Vishwa Kalyan Rashtriya Manav Samaj Party",
  "Bahujan Samaj Party",
  "Independent",
  "Moulik Adhikar Party",
  "Yuga Thulasi Party",
  "Bharatiya Janata Party",
  "None of the Above",
  "Independent",
  "Peace Party",
  "Rashtriya Jantantrik Bharat Vikas Party",
  "Bahujan Samaj Party",
  "Pragatisheel Manav Samaj Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Aawami Pichhada Party",
  "Akhil Bhartiya Hamara Samaj Party",
  "Independent",
  "Janta Kranti Party (Rashtravadi)",
  "Independent",
  "Jan Raajya Party",
  "Samajhdar Party",
  "Samajwadi Party",
  "Independent",
  "Mang Samaj Party",
  "Communist Party of India",
  "Independent",
  "Azad Adhikar Sena",
  "Moolniwasi Samaj Party",
  "Independent",
  "Bhartiya Sabka Dal",
  "Sardar Patel Siddhant Party",
  "Independent",
  "Suheldev Bharatiya Samaj Party",
  "Janlok Vikas Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Bhartiya Shakti Chetna Party",
  "Independent",
  "Bhartiya Uday Nirman Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "Bhagidari Party(P)",
  "Bhartiya Sarvdharm Party",
  "Independent",
  "Bharatiya Yuva Jan Ekta Party",
  "Independent",
  "Mera Adhikaar Rashtriya Dal",
  "Independent",
  "Al-Hind Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Bhartiya Shakti Chetna Party",
  "Independent",
  "Rashtra Uday Party",
  "Independent",
  "Independent",
  "Eklavya Samaj Party",
  "Spashtwadi Jan Aadhar Party",
  "Al-Hind Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Peoples Party of India (Democratic)",
  "Independent",
  "Justice Party",
  "Independent",
  "Naari Nar Rakshak Party",
  "Bhartiya Krishak Dal",
  "Independent",
  "Lok Jan Sangharsh Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Swaraj Bhartiya Nyay Party",
  "Independent",
  "Rashtra Uday Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Bhartiya Shakti Chetna Party",
  "None of the Above",
  "Apna Dal (Kamerawadi)",
  "Bharatiya Janata Party",
  "Pachchasi Parivartan Samaj Party",
  "Sardar Patel Siddhant Party",
  "Independent",
  "Samaj Vikas Kranti Party",
  "Independent",
  "Samajwadi Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Moulik Adhikar Party",
  "Independent",
  "Bhagidari Party(P)",
  "Independent",
  "Bahujan Samaj Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Apna Dal (Kamerawadi)",
  "Al-Hind Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Social Democratic Party Of India",
  "Independent",
  "Independent",
  "Azad Adhikar Sena",
  "Independent",
  "Akhand Bharat Swatantra Party",
  "Independent",
  "Rashtriya Mazdoor Ekta Party",
  "Independent",
  "Independent",
  "Aapki Apni Party (Peoples)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Rashtriya Shoshit Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "All India Forward Bloc",
  "Bharatiya Kisan Parivartan Party",
  "Bhartiya Krishak Dal",
  "Independent",
  "Bhartiya Shakti Chetna Party",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Sabhi Jan Party",
  "Independent",
  "Independent",
  "Independent",
  "Proutist Bloc, India",
  "Independent",
  "All India Forward Bloc",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Apna Dal (Kamerawadi)",
  "Independent",
  "Independent",
  "Manavtawadi Samaj Party",
  "Bhartiya Shakti Chetna Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Parivartan Samaj Party",
  "Independent",
  "Rashtriya Shoshit Samaj Party",
  "Independent",
  "Janta Kranti Party",
  "Rashtriya Vikalp Party",
  "Uttar Pradesh Republican Party",
  "Netaji Subhash Chander Bose Rashtriya Azad Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Rashtriya Shoshit Samaj Party",
  "Bhartiya Lok Nayak Party",
  "Azad Adhikar Sena",
  "Independent",
  "Subhashwadi Bhartiya Samajwadi Party (Subhas Party)",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Communist Party of India",
  "Independent",
  "Janta Kranti Party (Rashtravadi)",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Social Democratic Party Of India",
  "Independent",
  "Sarvar Party",
  "Mera Adhikaar Rashtriya Dal",
  "Independent",
  "Kisan Vishwa Party",
  "Hindu Samaj Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Samaj Parivartan Party",
  "Independent",
  "Independent",
  "Prabuddhwadi Bahujan Morcha",
  "Rashtra Uday Party",
  "Azad Samaj Party",
  "Sardar Patel Siddhant Party",
  "Prithviraj Janshakti Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Abhay Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Sardar Patel Siddhant Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Voters Party  International",
  "Bhartiya Shakti Chetna Party",
  "Independent",
  "Sarva Samaj Janata Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Rashtriya Samta Vikas Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Rashtriya Shoshit Samaj Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Rashtriya Shoshit Samaj Party",
  "Sabse Achchhi Party",
  "Social Democratic Party Of India",
  "Majloom Samaj Party",
  "Jai Hind National Party",
  "None of the Above",
  "Samajwadi Party",
  "Apna Dal (Soneylal)",
  "Bahujan Samaj Party",
  "Apna Dal (Kamerawadi)",
  "Independent",
  "Independent",
  "Eklavya Samaj Party",
  "Rashtriya Samaj Paksha",
  "All India Forward Bloc",
  "Purvanchal Mahapanchayat",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Bhartiya Shakti Chetna Party",
  "Independent",
  "Naari Nar Rakshak Party",
  "Independent",
  "Rashtriya Janshakti Samaj Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Rashtriya Samaj Paksha",
  "Aam Janta Party (India)",
  "Peoples Party of India (Democratic)",
  "Independent",
  "Sardar Patel Siddhant Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Apna Haq Party",
  "Bharatiya Bahujan Samta Party",
  "Independent",
  "Independent",
  "Independent",
  "Samata Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Rashtriya Congress(J) Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Vishal Janta Party",
  "Independent",
  "Rashtrawadi Janlok Party (Satya)",
  "Jai Samta Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Aazad Samaj Party (Kanshi Ram)",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Apna Dal (Kamerawadi)",
  "Pragatisheel Samaj Party",
  "Bahujan Awam Party",
  "Independent",
  "Independent",
  "Independent",
  "Bhagidari Party(P)",
  "Peoples Party of India (Democratic)",
  "Subhashwadi Bhartiya Samajwadi Party (Subhas Party)",
  "Prabuddhwadi Bahujan Morcha",
  "Yuva Vikas Party",
  "Sardar Patel Siddhant Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Independent",
  "Bhartiya Krishak Dal",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Rashtriya Samaj Dal (R)",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Hindustan Samaj Party",
  "Moulik Adhikar Party",
  "National Jan Dal",
  "Independent",
  "Rashtra Uday Party",
  "Independent",
  "Sanatan Sanskriti Raksha Dal",
  "Apna Dal (Kamerawadi)",
  "Bhartiya Lokmat Rashtrwadi Party",
  "Independent",
  "Manavtawadi Samaj Party",
  "Samajhdar Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Log Party",
  "Rastriya Atal Janta Party",
  "Independent",
  "Independent",
  "Sardar Patel Siddhant Party",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Akhil Bhartiya Apna Dal",
  "Independent",
  "Bhartiya Panchsheel Party",
  "Manavtawadi Samaj Party",
  "Apna Dal (Kamerawadi)",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Minorities Democratic Party",
  "Independent",
  "None of the Above",
  "Samajwadi Party",
  "Apna Dal (Soneylal)",
  "Bahujan Samaj Party",
  "Communist Party of India",
  "Rashtriya Samanta Dal",
  "Janhit Sankalp Party",
  "Independent",
  "Independent",
  "Rashtriya Samaj Paksha",
  "Sardar Patel Siddhant Party",
  "Rashtriya Samaj Dal (R)",
  "Janta Kranti Party (Rashtravadi)",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Akhil Bhartiya Parivar Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Bahujan Samaj Party",
  "Independent",
  "Sardar Patel Siddhant Party",
  "Janta Kranti Party (Rashtravadi)",
  "Samajwadi Party",
  "Independent",
  "Independent",
  "Akhil Bhartiya Sarvjan Hit Party",
  "Bharatiya Janata Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "Janta Shashan Party",
  "Kisan Kranti Dal",
  "Peace Party",
  "Independent",
  "Log Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Pragatisheel Samaj Party",
  "Independent",
  "Sardar Patel Siddhant Party",
  "Independent",
  "Independent",
  "Sarvjan Awaz Party",
  "Independent",
  "Naki Bharatiya Ekta Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Rashtriya Sanatan Party",
  "Independent",
  "Independent",
  "Independent",
  "Sardar Patel Siddhant Party",
  "Independent",
  "Manav Kranti Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Peace Party",
  "Independent",
  "Independent",
  "Aam Janta Party (India)",
  "Samyak Party",
  "Independent",
  "Kisan Mazdoor Sangharsh Party",
  "Rashtriya Janta Party",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Apna Dal (Kamerawadi)",
  "Aazad Samaj Party (Kanshi Ram)",
  "Independent",
  "Rashtriya Shoshit Samaj Party",
  "Sardar Patel Siddhant Party",
  "None of the Above",
  "Samajwadi Party",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Apna Desh Party",
  "Independent",
  "Independent",
  "Azad Party",
  "Most Backward Classes Of India",
  "Sardar Patel Siddhant Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Samajwadi Party",
  "Bahujan Samaj Party",
  "Parcham Party of India",
  "Independent",
  "Independent",
  "Bhartiya Shakti Chetna Party",
  "Independent",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Yuga Thulasi Party",
  "Apna Dal (Kamerawadi)",
  "Independent",
  "Independent",
  "None of the Above",
  "Bharatiya Janata Party",
  "Peoples Party of India (Democratic)",
  "Uttarakhand Parivartan Party",
  "Bahujan Samaj Party",
  "Independent",
  "Bahujan Mukti Party",
  "Indian National Congress",
  "None of the Above",
  "Peoples Party of India (Democratic)",
  "Bharatiya Janata Party",
  "Uttarakhand Samanta Party",
  "Sainik Samaj Party",
  "Independent",
  "Akhil Bhartiya Parivar Party",
  "Independent",
  "Indian National Congress",
  "Bahujan Mukti Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Uttarakhand Kranti Dal",
  "Independent",
  "Bahujan Samaj Party",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Peoples Party of India (Democratic)",
  "Independent",
  "Uttarakhand Samanta Party",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Bhartiya Rashtriya Ekta Dal",
  "Independent",
  "Uttarakhand Kranti Dal",
  "Independent",
  "Indian National Congress",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Bhartiya Shakti Chetna Party",
  "Bharat Ki Lok Jimmedar Party",
  "Akhil Bhartiya Parivar Party",
  "Bharatiya Janata Party",
  "Independent",
  "Uttarakhand Kranti Dal",
  "Peoples Party of India (Democratic)",
  "Indian National Congress",
  "None of the Above",
  "Independent",
  "Indian National Congress",
  "Independent",
  "Peoples Party of India (Democratic)",
  "Rashtriya Uttarakhand Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Bhartiya Rashtriya Ekta Dal",
  "Bharatiya Janata Party",
  "None of the Above",
  "Independent",
  "All India Trinamool Congress",
  "Kisan Mazdoor Sangharsh Party",
  "North Bengal People’s Party",
  "Revolutionary Socialist Party",
  "Gana Suraksha Party",
  "Bharatiya Janata Party",
  "Independent",
  "Kamatapur People’s Party (United)",
  "Bahujan Samaj Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "All India Trinamool Congress",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Communist Party of India  (Marxist)",
  "None of the Above",
  "Bharatiya Janata Party",
  "All India Trinamool Congress",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Independent",
  "Social Democratic Party Of India",
  "All India Arya Mahasabha",
  "Independent",
  "Independent",
  "Independent",
  "All India Trinamool Congress",
  "Jai Prakash Janata Dal",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Indian National Congress",
  "Indian National Socialistic Action Forces",
  "Independent",
  "Bharatiya Janata Party",
  "Bahujan Samaj Party",
  "Independent",
  "None of the Above",
  "Ambedkarite Party of India",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "All India Secular Front",
  "Bhumiputra United Party",
  "Independent",
  "Independent",
  "Independent",
  "All India Trinamool Congress",
  "Kamatapur People’s Party (United)",
  "Bharatiya Janata Party",
  "Revolutionary Socialist Party",
  "Independent",
  "Bahujan Samaj Party",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Indian National Congress",
  "All India Secular Front",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "All India Trinamool Congress",
  "Guruchand Sena Dal",
  "Independent",
  "Independent",
  "Party for Democratic Socialism",
  "Independent",
  "Bahujan Samaj Party",
  "None of the Above",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Kisan Mazdoor Sangharsh Party",
  "Ambedkarite Party of India",
  "Independent",
  "Communist Party of India  (Marxist)",
  "None of the Above",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "All India Trinamool Congress",
  "Independent",
  "All India Forward Bloc",
  "Mulnibasi Party of India",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "All India Secular Front",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Bharatiya Janata Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist-Leninist)  (Liberation)",
  "All India Trinamool Congress",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bahujan Samaj Party",
  "None of the Above",
  "All India Trinamool Congress",
  "Independent",
  "The National Road Map Party of India",
  "Communist Party of India  (Marxist)",
  "Bharatiya Janata Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bahujan Samaj Party",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "All India Secular Front",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "Bharatiya Janata Party",
  "None of the Above",
  "Independent",
  "Communist Party of India  (Marxist)",
  "Mulnibasi Party of India",
  "Independent",
  "Bharatheeya Jawan Kisan Party",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "All India Secular Front",
  "Independent",
  "Bharatiya Janata Party",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Bharatiya National Janata Dal",
  "Indian National Socialistic Action Forces",
  "All India Trinamool Congress",
  "Independent",
  "Indian National Congress",
  "Ambedkarite Party of India",
  "All India Arya Mahasabha",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Bahujan Samaj Party",
  "None of the Above",
  "All India Trinamool Congress",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist)",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "None of the Above",
  "All India Trinamool Congress",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Bahujan Samaj Party",
  "Mulnibasi Party of India",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Hindustan Shakti Sena",
  "None of the Above",
  "All India Trinamool Congress",
  "Bharatiya Janata Party",
  "All India Forward Bloc",
  "Indian National Congress",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Kamatapur People’s Party (United)",
  "Independent",
  "Independent",
  "None of the Above",
  "North Bengal People’s Party",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Indian National Congress",
  "Gorkha Rashtriya Congress",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "Ambedkarite Party of India",
  "Kisan Mazdoor Sangharsh Party",
  "Independent",
  "Kamatapur People’s Party (United)",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "All India Trinamool Congress",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Independent",
  "All India Secular Front",
  "Indian National Socialistic Action Forces",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Mera Bharat Mahan Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "All India Trinamool Congress",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Mulnibasi Party of India",
  "Communist Party of India  (Marxist)",
  "Democratic Socialist Party of India",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "None of the Above",
  "All India Trinamool Congress",
  "Independent",
  "Communist Party of India",
  "Bahujan Samaj Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bharatiya Janata Party",
  "None of the Above",
  "Independent",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Bharatiya National Janata Dal",
  "Independent",
  "All India Trinamool Congress",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "All India Arya Mahasabha",
  "Independent",
  "Communist Party of India  (Marxist)",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Bharatiya Janata Party",
  "None of the Above",
  "All India Trinamool Congress",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Independent",
  "Independent",
  "All India Secular Front",
  "Mulnibasi Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Independent",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Bharatiya Janata Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Mulnibasi Party of India",
  "All India Trinamool Congress",
  "Independent",
  "Kamatapur People’s Party (United)",
  "Independent",
  "Independent",
  "Communist Party of India  (Marxist)",
  "None of the Above",
  "Independent",
  "All India Trinamool Congress",
  "Indian National Congress",
  "All India Secular Front",
  "Bharatheeya Jawan Kisan Party",
  "Social Democratic Party Of India",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Bhartiya Lokmat Rashtrwadi Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Independent",
  "All India Trinamool Congress",
  "Mulnibasi Party of India",
  "Independent",
  "Revolutionary Socialist Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "All India Secular Front",
  "Bharatiya Janata Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Jharkhand People's Party",
  "Ambedkarite Party of India",
  "Independent",
  "Communist Party of India  (Marxist)",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "All India Secular Front",
  "Independent",
  "Bharatiya Janata Party",
  "None of the Above",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "All India Trinamool Congress",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Indian National Congress",
  "None of the Above",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Kisan Mazdoor Sangharsh Party",
  "Independent",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Social Democratic Party Of India",
  "Independent",
  "Right to Recall Party",
  "Independent",
  "All India Trinamool Congress",
  "None of the Above",
  "Independent",
  "All India Trinamool Congress",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Independent",
  "Mission Naya Digant Party",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Pyramid Party of India",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Indian National Congress",
  "None of the Above",
  "Independent",
  "All India Trinamool Congress",
  "All India Secular Front",
  "Independent",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Bharatiya Janata Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "None of the Above",
  "Indian National Congress",
  "Bharatiya Janata Party",
  "All India Trinamool Congress",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Jan Sangh Party",
  "Independent",
  "Bhartiya Lokmat Rashtrwadi Party",
  "Ambedkarite Party of India",
  "Social Democratic Party Of India",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Rashtriya Secular Majlis Party",
  "Jamat-E-Seratul Mustakim",
  "None of the Above",
  "Bharatiya Janata Party",
  "All India Trinamool Congress",
  "Indian National Congress",
  "Independent",
  "Ambedkarite Party of India",
  "Independent",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Kamatapur People’s Party (United)",
  "Independent",
  "All India Secular Front",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Jan Sangh Party",
  "None of the Above",
  "Independent",
  "Bahujan Samaj Party",
  "Party for Democratic Socialism",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist)",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "All India Secular Front",
  "Mulnibasi Party of India",
  "Independent",
  "All India Trinamool Congress",
  "None of the Above",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bahujan Samaj Party",
  "Independent",
  "Independent",
  "Communist Party of India",
  "All India Trinamool Congress",
  "None of the Above",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Independent",
  "Bharatiya Janata Party",
  "Communist Party of India  (Marxist)",
  "Bhartiya Lokmat Rashtrwadi Party",
  "All India Secular Front",
  "Social Democratic Party Of India",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Party for Democratic Socialism",
  "All India Trinamool Congress",
  "Independent",
  "All India Forward Bloc",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bahujan Samaj Party",
  "Independent",
  "Indian National Congress",
  "None of the Above",
  "Jai Prakash Janata Dal",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "All India Trinamool Congress",
  "Independent",
  "Bhumiputra United Party",
  "Independent",
  "India Manus Party",
  "North Bengal People’s Party",
  "Independent",
  "Independent",
  "Bahujan Samaj Party",
  "Ambedkarite Party of India",
  "Independent",
  "Independent",
  "Independent",
  "Bharatiya Janata Party",
  "Indian National Congress",
  "Independent",
  "Independent",
  "None of the Above",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "All India Trinamool Congress",
  "Bahujan Samaj Party",
  "Bharatiya Janata Party",
  "Independent",
  "Independent",
  "Communist Party of India  (Marxist)",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Independent",
  "Bahujan Maha Party",
  "Bahujan Samaj Party",
  "Independent",
  "All India Trinamool Congress",
  "Independent",
  "All India Secular Front",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Communist Party of India  (Marxist)",
  "None of the Above",
  "Bharatiya Janata Party",
  "Independent",
  "All India Secular Front",
  "Communist Party of India  (Marxist)",
  "All India Trinamool Congress",
  "Independent",
  "Independent",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "Bahujan Samaj Party",
  "None of the Above",
  "Independent",
  "Bharatiya Janata Party",
  "Indian Unity Centre",
  "Socialist Unity Centre Of India (COMMUNIST)",
  "All India Trinamool Congress",
  "Independent",
  "Indian National Congress",
  "Independent",
  "All India Secular Front",
  "Bharatiya Nyay-Adhikar Raksha Party",
  "Independent",
  "Bahujan Samaj Party",
  "None of the Above"
]

const party = {};
for(let itm of partyArr){
  party[itm] = 0;
}
//console.log(Object.keys(party));


const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: process.env.MYSQL_PASSWORD,
  database: 'e2024'
});

// Connect to the database
connection.connect((err) => {
  if (err) {
    console.error('Error connecting to database: ' + err.stack);
    return;
  }
  console.log('Connected to database as id ' + connection.threadId);
});
let count = 1;
for(let itm in party){
  connection.query(`select name from party where name = "${itm}"`,(err,result)=>{
    if (err) {
      console.log(err);
      return;
    }
    console.log(itm+" "+" "+result[0].name+" "+count);
    count++;
  });
}
connection.end();